/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextFieldComponent: typeof import('./src/components/TextFieldComponent.vue')['default']
    TitleComponent: typeof import('./src/components/TitleComponent.vue')['default']
  }
}
